# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [9]:
# Your code here
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [10]:
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [11]:
df.shape

(4008, 11)

In [12]:
df.info()
print()
print("Sugerencias\n"
    "- Number of Open Complaints debería ser un int\n"
    "- Customer Lifetime Value debería ser un float\n"
    "* En vez de df.info() podemos usar df.dtypes()")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

Sugerencias
- Number of Open Complaints debería ser un int
- Customer Lifetime Value debería ser un float
* En vez de df.info() podemos usar df.dtypes()

In [13]:
df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [14]:
print("Con el .nunique(), parece que ST, Gender, Education, Number of Open complaints,Policy Type y Vehicle Class, son categóricas")
print()

categorias = ["ST", "GENDER", "Education", "Policy Type", "Vehicle Class"]
print(df[categorias].describe())
print()

numeric_col = df.select_dtypes(include="number").columns
rango = df[numeric_col].max() - df[numeric_col].min()
print("El rango es:\n", 
      rango)
print("En conclusión, el Income y el Monthly Premium Auto, son muy grandes por lo que nos indica que hay muchos tipos de clientes. El Total Claim Amount es grande pero no tanto, así que no hay tanta diferencia en la suma de siniestros\n"
      "Como Customer Lifetime Value te lo da en % y Number of open complaints en otro formato, habría que convertilo a float")

Con el .nunique(), parece que ST, Gender, Education, Number of Open complaints,Policy Type y Vehicle Class, son categóricas

            ST GENDER Education    Policy Type  Vehicle Class
count     1071    954      1071           1071           1071
unique       8      5         6              3              6
top     Oregon      F  Bachelor  Personal Auto  Four-Door Car
freq       320    457       324            780            576

El rango es:
 Income                  99960.000000
Monthly Premium Auto    35293.000000
Total Claim Amount       2892.857571
dtype: float64
En conclusión, el Income y el Monthly Premium Auto, son muy grandes por lo que nos indica que hay muchos tipos de clientes. El Total Claim Amount es grande pero no tanto, así que no hay tanta diferencia en la suma de siniestros
Como Customer Lifetime Value te lo da en % y Number of open complaints en otro formato, habría que convertilo a float

In [15]:
df.describe(include='all')

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
count,1071,1071,954,1071,1068,1071.000000,1071.000000,1071,1071,1071,1071.000000
unique,1071,8,5,6,1027,NaN,NaN,6,3,6,NaN
top,RB50392,Oregon,F,Bachelor,445811.34%,NaN,NaN,1/0/00,Personal Auto,Four-Door Car,NaN
freq,1,320,457,324,4,NaN,NaN,830,780,576,NaN
mean,NaN,NaN,NaN,NaN,NaN,39295.701214,193.234360,NaN,NaN,NaN,404.986909
std,NaN,NaN,NaN,NaN,NaN,30469.427060,1601.190369,NaN,NaN,NaN,293.027260
min,NaN,NaN,NaN,NaN,NaN,0.000000,61.000000,NaN,NaN,NaN,0.382107
25%,NaN,NaN,NaN,NaN,NaN,14072.000000,68.000000,NaN,NaN,NaN,202.157702
50%,NaN,NaN,NaN,NaN,NaN,36234.000000,83.000000,NaN,NaN,NaN,354.729129
75%,NaN,NaN,NaN,NaN,NaN,64631.000000,109.500000,NaN,NaN,NaN,532.800000
max,NaN,NaN,NaN,NaN,NaN,99960.000000,35354.000000,NaN,NaN,NaN,2893.239678

In [16]:
print("Conclusiones columnas numéricas:\n"
      "- La media del income es casi 40000\n"
      "- Se paga poco de Monthly Premium Auto\n"
      "- Por cliente, la suma media del valor de todas las reclamaciones es de unos 400\n")
print("Conclusiones columnas categóricas:\n"
      "- La moda, lo más común es el estado de Oregon\n"
      "- En cuanto a Masculino o Femenino, están muy parejos\n"
      "- Lo más habitual es tener unca carrera\n"
      "- Es muy común tener un coche de 4 puertas y tener contratado de poliza el tipo Personal Auto")

Conclusiones columnas numéricas:
- La media del income es casi 40000
- Se paga poco de Monthly Premium Auto
- Por cliente, la suma media del valor de todas las reclamaciones es de unos 400

Conclusiones columnas categóricas:
- La moda, lo más común es el estado de Oregon
- En cuanto a Masculino o Femenino, están muy parejos
- Lo más habitual es tener unca carrera
- Es muy común tener un coche de 4 puertas y tener contratado de poliza el tipo Personal Auto

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [17]:
# Your code here
df["ST"].value_counts(ascending=True).head(5)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [18]:
# Your code here
numero_polizas = df["Policy Type"].value_counts()
print(numero_polizas)
print("El policy type con el mayor número es Personal Auto, con:", numero_polizas.max())
# Otra opción es numero_polizas = df.value_counts("Policy Type")

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
El policy type con el mayor número es Personal Auto, con: 780

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [19]:
# Your code here
personal_auto_policies = df.loc[df['Policy Type'] == 'Personal Auto']
corporate_auto_policies = df.loc[df['Policy Type'] == 'Corporate Auto']

In [ ]:
print("El ingreso medio del la Personal Auto Policy es:", personal_auto_policies['Income'].mean().round(2))
#Con el .round(2) nos pone solo 2 decimales, si queremos más cambiamos el número

El ingreso medio del la Personal Auto Policy es: 38180.7

In [21]:
print("El ingreso medio del la Corporate Auto Policy es:",corporate_auto_policies['Income'].mean().round(2))

El ingreso medio del la Corporate Auto Policy es: 41390.31

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [22]:
# Your code here
print(df['Total Claim Amount'].describe())

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64